allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@nuxt/image@2.1.0'
  - '@vueuse/core@14.4.0'
  - '@vueuse/metadata@14.4.0'
  - '@vueuse/nuxt@14.4.0'
  - '@vueuse/shared@14.4.0'
  - ipx@4.0.0-beta.1
